#数据源配置
spring:
    datasource:
      username: root
      password: root
      url:  jdbc:mysql://127.0.0.1:3306/jpa
      driver-class-name: com.mysql.jdbc.Driver
    #jpa配置
    jpa:
      hibernate:
        #更新或创建数据表结构
        ddl-auto: update
        # create: 每次加载 Hibernate 时都会删除上一次生成的表，然后根据 model 类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
        # create-drop: 每次加载 Hibernate 时根据 model 类生成表，但是 sessionFactory 一关闭，表就自动删除。
        # update: 最常用的属性，第一次加载 Hibernate 时根据 model 类会自动建立起表的结构（前提是先建立好数据库），以后加载 Hibernate 时根据 model 类自动更新表结构，即使表结
        # 构改变了，但表中的行仍然存在，不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会。
        # validate: 每次加载 Hibernate 时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      #控制台显示sql语句
      show-sql: true
      properties:
        hibernate:
         format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
         descriptor:
           sql:
            BasicBinder: trace
