server:
  port: 8002

spring:
  application:
    name: provider-ticket

eureka:
  instance:
    prefer-ip-address: true #注册时使用服务ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/