#数据源配置
spring:
    datasource:
      username: root
      password: root
      url:  jdbc:mysql://192.168.0.110:3306/mybatis
      driver-class-name: com.mysql.jdbc.Driver
      # type: 改变默认数据库连接池
      type: com.alibaba.druid.pool.DruidDataSource

      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 日志文件使用slf4j
      #使用log4j，或其他需导入核心依赖
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      ###############以上为配置druid添加的配置########################################

      # 数据源初始化方式：ALWAYS（经常）  EMBEDDED（只初始化嵌入式数据源）  NEVER（从不）
      initialization-mode: never
      #自定义路径及sql文件名称
      schema:
        #如果需要接着添加文件名
        - classpath:sql/employee.sql
        - classpath:sql/department.sql
#配置mybatis的springboot识别
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml